# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Stewart Adcock
tagline:             ''
description:         ''
url:                 http://adcock.org.uk
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Stewart Adcock
  url:               http://adcock.org.uk
  email:             stewart@adcock.org.uk

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/stewartadcock/stewartadcock.github.io

# List of pages to include in the header of the website
pages_list:
  About:            '/about/'
  Posts:            '/posts/'
  Feed:             '/atom.xml'

# Allow URL redirects.
# See also: https://help.github.com/articles/redirects-on-github-pages/
gems:
  - jekyll-redirect-from
